name: payblocks

# App-level environment variables (available to all components)
envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: PAYLOAD_SECRET
    value: ${PAYLOAD_SECRET}
    type: SECRET
    scope: RUN_AND_BUILD_TIME
  - key: DATABASE_URI
    value: ${DATABASE_URI}
    type: SECRET
    scope: RUN_AND_BUILD_TIME
  - key: NEXT_PUBLIC_SERVER_URL
    value: ${NEXT_PUBLIC_SERVER_URL}
    scope: RUN_AND_BUILD_TIME
  - key: process.env.PAYLOAD_SECRET
    value: ${PAYLOAD_SECRET}
    type: SECRET
    scope: RUN_AND_BUILD_TIME
  - key: process.env.DATABASE_URI
    value: ${DATABASE_URI}
    type: SECRET
    scope: RUN_AND_BUILD_TIME
  - key: process.env.MONGODB_URI
    value: ${MONGODB_URI}
    type: SECRET
    scope: RUN_AND_BUILD_TIME

services:
  - name: web
    source_dir: /
    github:
      repo: matusbialko/trying-payblocks
      branch: main
    run_command: pnpm start
    environment_slug: node-js-20
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: PAYLOAD_SECRET
        value: ${PAYLOAD_SECRET}
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: DATABASE_URI
        value: ${DATABASE_URI}
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_SERVER_URL
        value: ${NEXT_PUBLIC_SERVER_URL}
        scope: RUN_AND_BUILD_TIME
      - key: process.env.PAYLOAD_SECRET
        value: ${PAYLOAD_SECRET}
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: process.env.DATABASE_URI
        value: ${DATABASE_URI}
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: process.env.MONGODB_URI
        value: ${MONGODB_URI}
        type: SECRET
        scope: RUN_AND_BUILD_TIME

    build_command: ./build.sh
