name: payblocks

services:
  - name: web
    source_dir: /
    github:
      repo: matusbialko/trying-payblocks
      branch: main
    run_command: pnpm start
    environment_slug: node-js-20
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: APP_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: PAYLOAD_SECRET
        value: ${PAYLOAD_SECRET}
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: DATABASE_URI
        value: ${DATABASE_URI}
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: MONGODB_URI
        value: ${MONGODB_URI}
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_SERVER_URL
        value: ${NEXT_PUBLIC_SERVER_URL}
        scope: RUN_AND_BUILD_TIME

    dockerfile_path: Dockerfile
    build_args:
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - DATABASE_URI=${DATABASE_URI}
      - MONGODB_URI=${MONGODB_URI}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
